#pragma once

#include <cstddef>

/**
* @brief ...
* 
* @param data p_data:...
* @param size p_size:...
* @param data_size p_data_size:...
* @param user_data p_user_data:...
* @return std::size_t
*/
std::size_t write_callback(void *data, std::size_t size, std::size_t data_size, void *user_data);



/**
* @brief ...
* 
* @param data p_data:...
* @param size p_size:...
* @param data_size p_data_size:...
* @param user_data p_user_data:...
* @return std::size_t
*/
std::size_t header_callback(void *data, std::size_t size, std::size_t data_size, void *user_data);
